In [1]:
import pandas as pd
from datetime import datetime

In [2]:
master = pd.read_excel('/home/ananta/personnel_study_material/practice-and-projects/Sample_data/APAC_THAILAND/Master City & Province 03.07.25 (4).xlsx',sheet_name='Thailand Geography Structure',header=1)

In [3]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7425 entries, 0 to 7424
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country Name          7425 non-null   object
 1   Country Code          7425 non-null   object
 2   Province Name (Eng)   7425 non-null   object
 3   Province Name (Thai)  7425 non-null   object
 4   Province Code         7425 non-null   object
 5   District Name (Eng)   7425 non-null   object
 6   District Name (Thai)  7425 non-null   object
 7   District Code         7425 non-null   object
 8   Sub-Dist. (Eng)       7425 non-null   object
 9   Sub-Dist. (Thai)      7365 non-null   object
 10  Sub Dist. Code        7425 non-null   object
 11  SEED
Region           2028 non-null   object
 12  SEED
Territory       2028 non-null   object
 13  SEED
Sub-Territory   1959 non-null   object
 14  DSM Name              2028 non-null   object
 15  MDO Name              2027 non-null   object
 16  CP
Region             4378 non-null   object
 17  CP
Territory          4371 non-null   object
 18  CP
Sub-Territory     4252 non-null   object
 19  DSM Name.1            4355 non-null   object
 20  MDO Name.1            4266 non-null   object
 21  Unnamed: 21           103 non-null    object
dtypes: object(22)
memory usage: 1.2+ MB

In [4]:
master.columns

Index(['Country Name', 'Country Code', 'Province Name (Eng)',
       'Province Name (Thai)', 'Province Code', 'District Name (Eng)',
       'District Name (Thai)', 'District Code', 'Sub-Dist. (Eng)',
       'Sub-Dist. (Thai)', 'Sub Dist. Code', 'SEED\nRegion',
       'SEED \nTerritory', 'SEED \nSub-Territory', 'DSM Name', 'MDO Name',
       'CP\nRegion', 'CP\nTerritory', 'CP \nSub-Territory', 'DSM Name.1',
       'MDO Name.1', 'Unnamed: 21'],
      dtype='object')

In [5]:
master.isna().sum()

Country Name               0
Country Code               0
Province Name (Eng)        0
Province Name (Thai)       0
Province Code              0
District Name (Eng)        0
District Name (Thai)       0
District Code              0
Sub-Dist. (Eng)            0
Sub-Dist. (Thai)          60
Sub Dist. Code             0
SEED\nRegion            5397
SEED \nTerritory        5397
SEED \nSub-Territory    5466
DSM Name                5397
MDO Name                5398
CP\nRegion              3047
CP\nTerritory           3054
CP \nSub-Territory      3173
DSM Name.1              3070
MDO Name.1              3159
Unnamed: 21             7322
dtype: int64

In [6]:
master.nunique()

Country Name               1
Country Code               1
Province Name (Eng)       77
Province Name (Thai)      77
Province Code             77
District Name (Eng)      918
District Name (Thai)     918
District Code            928
Sub-Dist. (Eng)         5650
Sub-Dist. (Thai)        5589
Sub Dist. Code          7425
SEED\nRegion               3
SEED \nTerritory           8
SEED \nSub-Territory      24
DSM Name                   8
MDO Name                  25
CP\nRegion                 3
CP\nTerritory              5
CP \nSub-Territory        19
DSM Name.1                 5
MDO Name.1                20
Unnamed: 21                3
dtype: int64

In [7]:
region = master['SEED\nRegion'].drop_duplicates().reset_index(drop=True).to_frame()
region.columns = ['Region']   # rename

In [8]:
region

        Region
0  Lower North
1   North East
2  Upper North
3          NaN

In [9]:
region['BU'] = 'seed'

In [10]:
region['BUID'] = 2

In [11]:
region_cp = master['CP\nRegion'].drop_duplicates().reset_index(drop=True).to_frame()
region_cp.columns = ['Region']   # rename

In [12]:
region_cp['BU'] = 'cp'

In [13]:
region_cp['BUID'] = 1

In [14]:
result = pd.concat([region, region_cp], ignore_index=True)

In [15]:
result = result.dropna(subset=['Region'])

In [16]:
result

        Region    BU  BUID
0  Lower North  seed     2
1   North East  seed     2
2  Upper North  seed     2
4  Lower North    cp     1
5      Central    cp     1
7   North East    cp     1

In [17]:
result.columns

Index(['Region', 'BU', 'BUID'], dtype='object')

In [18]:
result = result.reset_index()
del result['index']
result = result.reset_index()
result = result.rename(columns={'index':'region_id'})
result['region_id'] = result['region_id'] +1 
result.head(10)

   region_id       Region    BU  BUID
0          1  Lower North  seed     2
1          2   North East  seed     2
2          3  Upper North  seed     2
3          4  Lower North    cp     1
4          5      Central    cp     1
5          6   North East    cp     1

In [19]:
result['isActive'] = 1
result['createdon']= ''
result['modifiedon']= ''
result['createdby']= 'Admin'
result['modifiedby']= ''
result['countryId'] = 3
result

,region_id,Region,BU,BUID,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,Lower North,seed,2,1,,,Admin,,3
1,2,North East,seed,2,1,,,Admin,,3
2,3,Upper North,seed,2,1,,,Admin,,3
3,4,Lower North,cp,1,1,,,Admin,,3
4,5,Central,cp,1,1,,,Admin,,3
5,6,North East,cp,1,1,,,Admin,,3

In [20]:
result['createdon']= datetime.now()
result['modifiedon'] = pd.to_datetime(result['modifiedon'],errors = 'coerce')
result['createdon'] = pd.to_datetime(result['createdon'],errors = 'coerce')
result

,region_id,Region,BU,BUID,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,Lower North,seed,2,1,2025-11-27 16:33:57.845545,NaT,Admin,,3
1,2,North East,seed,2,1,2025-11-27 16:33:57.845545,NaT,Admin,,3
2,3,Upper North,seed,2,1,2025-11-27 16:33:57.845545,NaT,Admin,,3
3,4,Lower North,cp,1,1,2025-11-27 16:33:57.845545,NaT,Admin,,3
4,5,Central,cp,1,1,2025-11-27 16:33:57.845545,NaT,Admin,,3
5,6,North East,cp,1,1,2025-11-27 16:33:57.845545,NaT,Admin,,3

In [21]:
provience_master = master[['Province Name (Eng)',
                           'Province Name (Thai)',
                           'Province Code']].drop_duplicates().reset_index(drop=True)

In [22]:
provience_master['Province Name (Eng)'] = provience_master['Province Name (Eng)'].str.strip().str.upper()
provience_master['Province Name (Thai)'] = provience_master['Province Name (Thai)'].str.strip().str.upper()
provience_master['Province Code'] = provience_master['Province Code'].str.strip().str.upper()

In [23]:
provience_master.columns

Index(['Province Name (Eng)', 'Province Name (Thai)', 'Province Code'], dtype='object')

In [24]:
provience_master.isna().sum()

Province Name (Eng)     0
Province Name (Thai)    0
Province Code           0
dtype: int64

In [25]:
provience_master.nunique()

Province Name (Eng)     77
Province Name (Thai)    77
Province Code           77
dtype: int64

In [26]:
provience_master = provience_master.reset_index()
del provience_master['index']
provience_master = provience_master.reset_index()
provience_master = provience_master.rename(columns={'index':'provience_id'})
provience_master['provience_id'] = provience_master['provience_id'] +1 
provience_master.head(10)

   provience_id Province Name (Eng) Province Name (Thai) Province Code
0             1            LOP BURI               ลพบุรี          TH16
1             2            SARABURI              สระบุรี          TH19
2             3        NAKHON SAWAN            นครสวรรค์          TH60
3             4         UTHAI THANI            อุทัยธานี          TH61
4             5        KANCHANABURI            กาญจนบุรี          TH71
5             6         SUPHAN BURI           สุพรรณบุรี          TH72
6             7   NAKHON RATCHASIMA           นครราชสีมา          TH30
7             8           SI SA KET             ศรีสะเกษ          TH33
8             9          CHAIYAPHUM              ชัยภูมิ          TH36
9            10          PHETCHABUN            เพชรบูรณ์          TH67

In [27]:
provience_master['isActive'] = 1
provience_master['createdon']= ''
provience_master['modifiedon']= ''
provience_master['createdby']= 'Admin'
provience_master['modifiedby']= ''
provience_master['countryId'] = 3
provience_master

,provience_id,Province Name (Eng),Province Name (Thai),Province Code,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,LOP BURI,ลพบุรี,TH16,1,,,Admin,,3
1,2,SARABURI,สระบุรี,TH19,1,,,Admin,,3
2,3,NAKHON SAWAN,นครสวรรค์,TH60,1,,,Admin,,3
3,4,UTHAI THANI,อุทัยธานี,TH61,1,,,Admin,,3
4,5,KANCHANABURI,กาญจนบุรี,TH71,1,,,Admin,,3
...,...,...,...,...,...,...,...,...,...,...
72,73,TRANG,ตรัง,TH92,1,,,Admin,,3
73,74,PHATTHALUNG,พัทลุง,TH93,1,,,Admin,,3
74,75,PATTANI,ปัตตานี,TH94,1,,,Admin,,3
75,76,YALA,ยะลา,TH95,1,,,Admin,,3
76,77,NARATHIWAT,นราธิวาส,TH96,1,,,Admin,,3

In [28]:
provience_master['createdon']= datetime.now()
provience_master['modifiedon'] = pd.to_datetime(provience_master['modifiedon'],errors = 'coerce')
provience_master['createdon'] = pd.to_datetime(provience_master['createdon'],errors = 'coerce')
provience_master

,provience_id,Province Name (Eng),Province Name (Thai),Province Code,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,LOP BURI,ลพบุรี,TH16,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
1,2,SARABURI,สระบุรี,TH19,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
2,3,NAKHON SAWAN,นครสวรรค์,TH60,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
3,4,UTHAI THANI,อุทัยธานี,TH61,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
4,5,KANCHANABURI,กาญจนบุรี,TH71,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
...,...,...,...,...,...,...,...,...,...,...
72,73,TRANG,ตรัง,TH92,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
73,74,PHATTHALUNG,พัทลุง,TH93,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
74,75,PATTANI,ปัตตานี,TH94,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
75,76,YALA,ยะลา,TH95,1,2025-11-27 16:34:06.023626,NaT,Admin,,3
76,77,NARATHIWAT,นราธิวาส,TH96,1,2025-11-27 16:34:06.023626,NaT,Admin,,3

In [29]:
provience_master.columns

Index(['provience_id', 'Province Name (Eng)', 'Province Name (Thai)',
       'Province Code', 'isActive', 'createdon', 'modifiedon', 'createdby',
       'modifiedby', 'countryId'],
      dtype='object')

In [30]:
provience_master.isna().sum()

provience_id             0
Province Name (Eng)      0
Province Name (Thai)     0
Province Code            0
isActive                 0
createdon                0
modifiedon              77
createdby                0
modifiedby               0
countryId                0
dtype: int64

Index(['Country Name', 'Country Code', 'Province Name (Eng)',
       'Province Name (Thai)', 'Province Code', 'District Name (Eng)',
       'District Name (Thai)', 'District Code', 'Sub-Dist. (Eng)',
       'Sub-Dist. (Thai)', 'Sub Dist. Code', 'SEED\nRegion',
       'SEED \nTerritory', 'SEED \nSub-Territory', 'DSM Name', 'MDO Name',
       'CP\nRegion', 'CP\nTerritory', 'CP \nSub-Territory', 'DSM Name.1',
       'MDO Name.1', 'Unnamed: 21'],
      dtype='object')

In [31]:
## 'CP\nTerritory','SEED \nTerritory',

In [32]:
Territory_cp = master['CP\nTerritory'].drop_duplicates().reset_index(drop=True).to_frame()
Territory_cp.columns = ['Territory']   # rename

In [33]:
Territory_cp['BU'] = 'cp'

In [34]:
Territory_cp['BUID'] = '1'

In [35]:
Territory_seed = master['SEED \nTerritory'].drop_duplicates().reset_index(drop=True).to_frame()
Territory_seed.columns = ['Territory']   # rename

In [36]:
Territory_seed['BU'] = 'seed'

In [37]:
Territory_seed['BUID'] = '2'

In [38]:
territory_master = pd.concat([Territory_cp, Territory_seed], ignore_index=True)

In [39]:
territory_master = territory_master.reset_index()
del territory_master['index']
territory_master = territory_master.reset_index()
territory_master = territory_master.rename(columns={'index':'territory_id'})
territory_master['territory_id'] = territory_master['territory_id'] +1 
territory_master.head(10)

   territory_id Territory    BU BUID
0             1       LN2    cp    1
1             2        C2    cp    1
2             3       NaN    cp    1
3             4        C1    cp    1
4             5       NE5    cp    1
5             6       LN1    cp    1
6             7       LN3  seed    2
7             8       NE1  seed    2
8             9       NE2  seed    2
9            10       NE3  seed    2

In [40]:
territory_master['isActive'] = 1
territory_master['createdon']= ''
territory_master['modifiedon']= ''
territory_master['createdby']= 'Admin'
territory_master['modifiedby']= ''
territory_master['countryId'] = 3
territory_master

,territory_id,Territory,BU,BUID,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,LN2,cp,1,1,,,Admin,,3
1,2,C2,cp,1,1,,,Admin,,3
2,3,NaN,cp,1,1,,,Admin,,3
3,4,C1,cp,1,1,,,Admin,,3
4,5,NE5,cp,1,1,,,Admin,,3
5,6,LN1,cp,1,1,,,Admin,,3
6,7,LN3,seed,2,1,,,Admin,,3
7,8,NE1,seed,2,1,,,Admin,,3
8,9,NE2,seed,2,1,,,Admin,,3
9,10,NE3,seed,2,1,,,Admin,,3
10,11,NE4,seed,2,1,,,Admin,,3
11,12,UN1,seed,2,1,,,Admin,,3
12,13,UN2,seed,2,1,,,Admin,,3
13,14,UN3,seed,2,1,,,Admin,,3
14,15,NaN,seed,2,1,,,Admin,,3

In [41]:
territory_master['createdon']= datetime.now()
territory_master['modifiedon'] = pd.to_datetime(territory_master['modifiedon'],errors = 'coerce')
territory_master['createdon'] = pd.to_datetime(territory_master['createdon'],errors = 'coerce')
territory_master

,territory_id,Territory,BU,BUID,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,LN2,cp,1,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
1,2,C2,cp,1,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
2,3,NaN,cp,1,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
3,4,C1,cp,1,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
4,5,NE5,cp,1,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
5,6,LN1,cp,1,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
6,7,LN3,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
7,8,NE1,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
8,9,NE2,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
9,10,NE3,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
10,11,NE4,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
11,12,UN1,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
12,13,UN2,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
13,14,UN3,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3
14,15,NaN,seed,2,1,2025-11-27 16:34:14.108520,NaT,Admin,,3

In [42]:
 'CP \nSub-Territory','SEED \nSub-Territory',

('CP \nSub-Territory', 'SEED \nSub-Territory')

In [43]:
Sub_territory_cp = master['CP \nSub-Territory'].drop_duplicates().reset_index(drop=True).to_frame()
Sub_territory_cp.columns = ['Sub_territory']   # rename

In [44]:
Sub_territory_cp['BU'] = 'cp'

In [45]:
Sub_territory_cp['BUID'] = '1'

In [46]:
Sub_territory_seed = master['SEED \nSub-Territory'].drop_duplicates().reset_index(drop=True).to_frame()
Sub_territory_seed.columns = ['Sub_territory']   # rename

In [47]:
Sub_territory_seed['BU'] = 'seed'

In [48]:
Sub_territory_seed['BUID'] = '2'

In [49]:
Sub_territory_master = pd.concat([Sub_territory_cp, Sub_territory_seed], ignore_index=True)

In [50]:
Sub_territory_master = Sub_territory_master.reset_index()
del Sub_territory_master['index']
Sub_territory_master = Sub_territory_master.reset_index()
Sub_territory_master = Sub_territory_master.rename(columns={'index':'territory_id'})
Sub_territory_master['territory_id'] = Sub_territory_master['territory_id'] +1 
Sub_territory_master.head(10)

   territory_id Sub_territory  BU BUID
0             1         LN2 B  cp    1
1             2          C2 B  cp    1
2             3         LN2 D  cp    1
3             4         LN2 C  cp    1
4             5         LN2 A  cp    1
5             6          C2 C  cp    1
6             7           NaN  cp    1
7             8          C1 A  cp    1
8             9         NE5 B  cp    1
9            10         NE5 A  cp    1

In [51]:
Sub_territory_master['isActive'] = 1
Sub_territory_master['createdon']= ''
Sub_territory_master['modifiedon']= ''
Sub_territory_master['createdby']= 'Admin'
Sub_territory_master['modifiedby']= ''
Sub_territory_master['countryId'] = 3
Sub_territory_master

,territory_id,Sub_territory,BU,BUID,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,LN2 B,cp,1,1,,,Admin,,3
1,2,C2 B,cp,1,1,,,Admin,,3
2,3,LN2 D,cp,1,1,,,Admin,,3
3,4,LN2 C,cp,1,1,,,Admin,,3
4,5,LN2 A,cp,1,1,,,Admin,,3
5,6,C2 C,cp,1,1,,,Admin,,3
6,7,NaN,cp,1,1,,,Admin,,3
7,8,C1 A,cp,1,1,,,Admin,,3
8,9,NE5 B,cp,1,1,,,Admin,,3
9,10,NE5 A,cp,1,1,,,Admin,,3
10,11,LN1 B,cp,1,1,,,Admin,,3
11,12,LN1 A,cp,1,1,,,Admin,,3
12,13,LN1 D,cp,1,1,,,Admin,,3
13,14,LN1 C,cp,1,1,,,Admin,,3
14,15,LN2 E,cp,1,1,,,Admin,,3
15,16,C2 A,cp,1,1,,,Admin,,3
16,17,C1 D,cp,1,1,,,Admin,,3
17,18,C1 C,cp,1,1,,,Admin,,3
18,19,C1 B,cp,1,1,,,Admin,,3
19,20,NE5 C,cp,1,1,,,Admin,,3
20,21,LN3 A,seed,2,1,,,Admin,,3
21,22,LN3 C,seed,2,1,,,Admin,,3
22,23,LN3 B,seed,2,1,,,Admin,,3
23,24,LN3 D,seed,2,1,,,Admin,,3
24,25,NE1 A,seed,2,1,,,Admin,,3
25,26,NE1 B,seed,2,1,,,Admin,,3
26,27,NE2 B,seed,2,1,,,Admin,,3
27,28,NE2 A,seed,2,1,,,Admin,,3
28,29,NaN,seed,2,1,,,Admin,,3
29,30,NE3 C,seed,2,1,,,Admin,,3
30,31,NE3 B,seed,2,1,,,Admin,,3
31,32,NE3 A,seed,2,1,,,Admin,,3
32,33,NE3 D,seed,2,1,,,Admin,,3
33,34,NE4 A,seed,2,1,,,Admin,,3
34,35,NE4 B,seed,2,1,,,Admin,,3
35,36,UN1 D,seed,2,1,,,Admin,,3
36,37,UN1 B,seed,2,1,,,Admin,,3
37,38,UN1 C,seed,2,1,,,Admin,,3
38,39,UN1 A,seed,2,1,,,Admin,,3
39,40,UN2 B,seed,2,1,,,Admin,,3
40,41,UN2 A,seed,2,1,,,Admin,,3
41,42,UN2 C,seed,2,1,,,Admin,,3
42,43,UN2 D,seed,2,1,,,Admin,,3
43,44,UN3 A,seed,2,1,,,Admin,,3
44,45,UN3 B,seed,2,1,,,Admin,,3

In [52]:
territory_master['createdon']= datetime.now()
territory_master['modifiedon'] = pd.to_datetime(territory_master['modifiedon'],errors = 'coerce')
territory_master['createdon'] = pd.to_datetime(territory_master['createdon'],errors = 'coerce')
territory_master

,territory_id,Territory,BU,BUID,isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,LN2,cp,1,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
1,2,C2,cp,1,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
2,3,NaN,cp,1,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
3,4,C1,cp,1,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
4,5,NE5,cp,1,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
5,6,LN1,cp,1,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
6,7,LN3,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
7,8,NE1,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
8,9,NE2,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
9,10,NE3,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
10,11,NE4,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
11,12,UN1,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
12,13,UN2,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
13,14,UN3,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3
14,15,NaN,seed,2,1,2025-11-27 16:34:21.102209,NaT,Admin,,3

Index(['Country Name', 'Country Code', 'Province Name (Eng)',
       'Province Name (Thai)', 'Province Code', 'District Name (Eng)',
       'District Name (Thai)', 'District Code', 'Sub-Dist. (Eng)',
       'Sub-Dist. (Thai)', 'Sub Dist. Code', 'SEED\nRegion',
       'SEED \nTerritory', 'SEED \nSub-Territory', 'DSM Name', 'MDO Name',
       'CP\nRegion', 'CP\nTerritory', 'CP \nSub-Territory', 'DSM Name.1',
       'MDO Name.1', 'Unnamed: 21'],
      dtype='object')

'District Name (Eng)', 'District Name (Thai)', 'District Code',

'Sub-Dist. (Eng)', 'Sub-Dist. (Thai)', 'Sub Dist. Code'

In [53]:
provience_master.columns

Index(['provience_id', 'Province Name (Eng)', 'Province Name (Thai)',
       'Province Code', 'isActive', 'createdon', 'modifiedon', 'createdby',
       'modifiedby', 'countryId'],
      dtype='object')

In [54]:
master.columns

Index(['Country Name', 'Country Code', 'Province Name (Eng)',
       'Province Name (Thai)', 'Province Code', 'District Name (Eng)',
       'District Name (Thai)', 'District Code', 'Sub-Dist. (Eng)',
       'Sub-Dist. (Thai)', 'Sub Dist. Code', 'SEED\nRegion',
       'SEED \nTerritory', 'SEED \nSub-Territory', 'DSM Name', 'MDO Name',
       'CP\nRegion', 'CP\nTerritory', 'CP \nSub-Territory', 'DSM Name.1',
       'MDO Name.1', 'Unnamed: 21'],
      dtype='object')

In [55]:
Dis_mas =  master[['Province Name (Eng)','Province Name (Thai)','District Name (Eng)','District Name (Thai)']].drop_duplicates(subset = 'District Name (Eng)')
Dis_mas

,Province Name (Eng),Province Name (Thai),District Name (Eng),District Name (Thai)
0,Lop Buri,ลพบุรี,Mueang Lop Buri,เมืองลพบุรี
24,Lop Buri,ลพบุรี,Phatthana Nikhom,พัฒนานิคม
33,Lop Buri,ลพบุรี,Khok Samrong,โคกสำโรง
46,Lop Buri,ลพบุรี,Chai Badan,ชัยบาดาล
63,Lop Buri,ลพบุรี,Tha Wung,ท่าวุ้ง
...,...,...,...,...
7403,Narathiwat,นราธิวาส,Sukhirin,สุคิริน
7408,Narathiwat,นราธิวาส,Su-Ngai Kolok,สุไหงโก-ลก
7412,Narathiwat,นราธิวาส,Su-Ngai Padi,สุไหงปาดี
7418,Narathiwat,นราธิวาส,Chanae,จะแนะ
7422,Narathiwat,นราธิวาส,Cho-Airong,เจาะไอร้อง

In [56]:
Dis_mas['District Name (Eng)'] = Dis_mas['District Name (Eng)'].str.strip().str.upper()
Dis_mas['District Name (Thai)'] = Dis_mas['District Name (Thai)'].str.strip().str.upper()
Dis_mas['Province Name (Eng)'] = Dis_mas['Province Name (Eng)'].str.strip().str.upper()
Dis_mas['Province Name (Thai)'] = Dis_mas['Province Name (Thai)'].str.strip().str.upper()

In [57]:
provience_master.columns

Index(['provience_id', 'Province Name (Eng)', 'Province Name (Thai)',
       'Province Code', 'isActive', 'createdon', 'modifiedon', 'createdby',
       'modifiedby', 'countryId'],
      dtype='object')

In [58]:
Dis_mas.columns

Index(['Province Name (Eng)', 'Province Name (Thai)', 'District Name (Eng)',
       'District Name (Thai)'],
      dtype='object')

In [59]:
Dis_mas = pd.merge(Dis_mas,provience_master[['provience_id', 'Province Name (Eng)']],on='Province Name (Eng)',how='left')
Dis_mas =  Dis_mas.rename(columns={'provience_id':'ProvinceID'})
Dis_mas

,Province Name (Eng),Province Name (Thai),District Name (Eng),District Name (Thai),ProvinceID
0,LOP BURI,ลพบุรี,MUEANG LOP BURI,เมืองลพบุรี,1
1,LOP BURI,ลพบุรี,PHATTHANA NIKHOM,พัฒนานิคม,1
2,LOP BURI,ลพบุรี,KHOK SAMRONG,โคกสำโรง,1
3,LOP BURI,ลพบุรี,CHAI BADAN,ชัยบาดาล,1
4,LOP BURI,ลพบุรี,THA WUNG,ท่าวุ้ง,1
...,...,...,...,...,...
913,NARATHIWAT,นราธิวาส,SUKHIRIN,สุคิริน,77
914,NARATHIWAT,นราธิวาส,SU-NGAI KOLOK,สุไหงโก-ลก,77
915,NARATHIWAT,นราธิวาส,SU-NGAI PADI,สุไหงปาดี,77
916,NARATHIWAT,นราธิวาส,CHANAE,จะแนะ,77
917,NARATHIWAT,นราธิวาส,CHO-AIRONG,เจาะไอร้อง,77

In [60]:
Dis_mas = Dis_mas[['ProvinceID', 'District Name (Eng)', 'District Name (Thai)']]

In [61]:
##[provinceId] needs to added inside Dis_mas

In [62]:
Dis_mas['District Name (Eng)'].nunique()

918

In [63]:
Dis_mas = Dis_mas.reset_index()
del Dis_mas['index']
Dis_mas = Dis_mas.reset_index()
Dis_mas = Dis_mas.rename(columns={'index':'district_id'})
Dis_mas['district_id'] = Dis_mas['district_id'] +1 
Dis_mas.head(10)

   district_id  ProvinceID District Name (Eng) District Name (Thai)
0            1           1     MUEANG LOP BURI          เมืองลพบุรี
1            2           1    PHATTHANA NIKHOM            พัฒนานิคม
2            3           1        KHOK SAMRONG             โคกสำโรง
3            4           1          CHAI BADAN             ชัยบาดาล
4            5           1            THA WUNG              ท่าวุ้ง
5            6           1              BAN MI             บ้านหมี่
6            7           1           THA LUANG              ท่าหลวง
7            8           1              SA BOT             สระโบสถ์
8            9           1        KHOK CHAROEN             โคกเจริญ
9           10           1          LAM SONTHI               ลำสนธิ

In [64]:
Dis_mas['isActive'] = 1
Dis_mas['createdon']= ''
Dis_mas['modifiedon']= ''
Dis_mas['createdby']= 'Admin'
Dis_mas['modifiedby']= ''
Dis_mas['countryId'] = 3
Dis_mas

,district_id,ProvinceID,District Name (Eng),District Name (Thai),isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,1,MUEANG LOP BURI,เมืองลพบุรี,1,,,Admin,,3
1,2,1,PHATTHANA NIKHOM,พัฒนานิคม,1,,,Admin,,3
2,3,1,KHOK SAMRONG,โคกสำโรง,1,,,Admin,,3
3,4,1,CHAI BADAN,ชัยบาดาล,1,,,Admin,,3
4,5,1,THA WUNG,ท่าวุ้ง,1,,,Admin,,3
...,...,...,...,...,...,...,...,...,...,...
913,914,77,SUKHIRIN,สุคิริน,1,,,Admin,,3
914,915,77,SU-NGAI KOLOK,สุไหงโก-ลก,1,,,Admin,,3
915,916,77,SU-NGAI PADI,สุไหงปาดี,1,,,Admin,,3
916,917,77,CHANAE,จะแนะ,1,,,Admin,,3
917,918,77,CHO-AIRONG,เจาะไอร้อง,1,,,Admin,,3

<!-- Index(['Country Name', 'Country Code', 'Province Name (Eng)',
       'Province Name (Thai)', 'Province Code', 'District Name (Eng)',
       'District Name (Thai)', 'District Code', 'Sub-Dist. (Eng)',
       'Sub-Dist. (Thai)', 'Sub Dist. Code', 'SEED\nRegion',
       'SEED \nTerritory', 'SEED \nSub-Territory', 'DSM Name', 'MDO Name',
       'CP\nRegion', 'CP\nTerritory', 'CP \nSub-Territory', 'DSM Name.1',
       'MDO Name.1', 'Unnamed: 21'],
      dtype='object') -->

In [65]:
Dis_mas['createdon']= datetime.now()
Dis_mas['modifiedon'] = pd.to_datetime(Dis_mas['modifiedon'],errors = 'coerce')
Dis_mas['createdon'] = pd.to_datetime(Dis_mas['createdon'],errors = 'coerce')
Dis_mas

,district_id,ProvinceID,District Name (Eng),District Name (Thai),isActive,createdon,modifiedon,createdby,modifiedby,countryId
0,1,1,MUEANG LOP BURI,เมืองลพบุรี,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
1,2,1,PHATTHANA NIKHOM,พัฒนานิคม,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
2,3,1,KHOK SAMRONG,โคกสำโรง,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
3,4,1,CHAI BADAN,ชัยบาดาล,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
4,5,1,THA WUNG,ท่าวุ้ง,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
...,...,...,...,...,...,...,...,...,...,...
913,914,77,SUKHIRIN,สุคิริน,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
914,915,77,SU-NGAI KOLOK,สุไหงโก-ลก,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
915,916,77,SU-NGAI PADI,สุไหงปาดี,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
916,917,77,CHANAE,จะแนะ,1,2025-11-27 16:34:35.313011,NaT,Admin,,3
917,918,77,CHO-AIRONG,เจาะไอร้อง,1,2025-11-27 16:34:35.313011,NaT,Admin,,3

In [66]:
sub_dis_mas = master[['District Name (Eng)','District Name (Thai)','Sub-Dist. (Eng)','Sub-Dist. (Thai)']].drop_duplicates(subset = 'Sub-Dist. (Eng)')
sub_dis_mas

     District Name (Eng) District Name (Thai) Sub-Dist. (Eng) Sub-Dist. (Thai)
0        Mueang Lop Buri          เมืองลพบุรี  Thale Chup Son        ทะเลชุบศร
1        Mueang Lop Buri          เมืองลพบุรี         Tha Hin           ท่าหิน
2        Mueang Lop Buri          เมืองลพบุรี          Kok Ko             กกโก
3        Mueang Lop Buri          เมืองลพบุรี      Kong Thanu          โก่งธนู
4        Mueang Lop Buri          เมืองลพบุรี  Khao Phra Ngam        เขาพระงาม
...                  ...                  ...             ...              ...
7419              Chanae                จะแนะ      Du Song Yo              NaN
7420              Chanae                จะแนะ     Phadung Mat         ผดุงมาตร
7422          Cho-Airong           เจาะไอร้อง           Chuap              จวบ
7423          Cho-Airong           เจาะไอร้อง          Bu Kit              NaN
7424          Cho-Airong           เจาะไอร้อง     Marue Bo Ok              NaN

[5650 rows x 4 columns]

In [67]:
sub_dis_mas.columns

Index(['District Name (Eng)', 'District Name (Thai)', 'Sub-Dist. (Eng)',
       'Sub-Dist. (Thai)'],
      dtype='object')

In [68]:
Dis_mas.columns

Index(['district_id', 'ProvinceID', 'District Name (Eng)',
       'District Name (Thai)', 'isActive', 'createdon', 'modifiedon',
       'createdby', 'modifiedby', 'countryId'],
      dtype='object')

In [70]:
sub_dis_mas['Sub-Dist. (Eng)'] = sub_dis_mas['Sub-Dist. (Eng)'].str.strip().str.upper()
sub_dis_mas['Sub-Dist. (Thai)'] = sub_dis_mas['Sub-Dist. (Thai)'].str.strip().str.upper()
sub_dis_mas['District Name (Eng)'] = sub_dis_mas['District Name (Eng)'].str.strip().str.upper()
sub_dis_mas['District Name (Thai)'] = sub_dis_mas['District Name (Thai)'].str.strip().str.upper()

In [71]:
sub_dis_mas = pd.merge(sub_dis_mas,Dis_mas[['district_id', 'District Name (Eng)']],on='District Name (Eng)',how='left')
sub_dis_mas =  sub_dis_mas.rename(columns={'ID':'DistrictID'})
sub_dis_mas

,District Name (Eng),District Name (Thai),Sub-Dist. (Eng),Sub-Dist. (Thai),district_id
0,MUEANG LOP BURI,เมืองลพบุรี,THALE CHUP SON,ทะเลชุบศร,1
1,MUEANG LOP BURI,เมืองลพบุรี,THA HIN,ท่าหิน,1
2,MUEANG LOP BURI,เมืองลพบุรี,KOK KO,กกโก,1
3,MUEANG LOP BURI,เมืองลพบุรี,KONG THANU,โก่งธนู,1
4,MUEANG LOP BURI,เมืองลพบุรี,KHAO PHRA NGAM,เขาพระงาม,1
...,...,...,...,...,...
5645,CHANAE,จะแนะ,DU SONG YO,NaN,917
5646,CHANAE,จะแนะ,PHADUNG MAT,ผดุงมาตร,917
5647,CHO-AIRONG,เจาะไอร้อง,CHUAP,จวบ,918
5648,CHO-AIRONG,เจาะไอร้อง,BU KIT,NaN,918
5649,CHO-AIRONG,เจาะไอร้อง,MARUE BO OK,NaN,918

In [72]:
sub_dis_mas.columns

Index(['District Name (Eng)', 'District Name (Thai)', 'Sub-Dist. (Eng)',
       'Sub-Dist. (Thai)', 'district_id'],
      dtype='object')

In [73]:
sub_dis_mas = sub_dis_mas[['district_id','Sub-Dist. (Eng)','Sub-Dist. (Thai)']]

In [75]:
# Index(['ID', 'District Name (Eng)', 'District Name (Thai)', 'Sub-Dist. (Eng)',
#        'Sub-Dist. (Thai)', 'isActive', 'createdon', 'modifiedon', 'createdby',
#        'modifiedby', 'CountryID'],
#       dtype='object')

##[districtId] needs to added inside sub_dis_mas

In [76]:
sub_dis_mas['Sub-Dist. (Eng)'].nunique()

5650

In [77]:
sub_dis_mas = sub_dis_mas.reset_index()
del sub_dis_mas['index']
sub_dis_mas = sub_dis_mas.reset_index()
sub_dis_mas = sub_dis_mas.rename(columns={'index':'ID'}) 
sub_dis_mas['ID']  = sub_dis_mas['ID'] + 1
sub_dis_mas

        ID  district_id Sub-Dist. (Eng) Sub-Dist. (Thai)
0        1            1  THALE CHUP SON        ทะเลชุบศร
1        2            1         THA HIN           ท่าหิน
2        3            1          KOK KO             กกโก
3        4            1      KONG THANU          โก่งธนู
4        5            1  KHAO PHRA NGAM        เขาพระงาม
...    ...          ...             ...              ...
5645  5646          917      DU SONG YO              NaN
5646  5647          917     PHADUNG MAT         ผดุงมาตร
5647  5648          918           CHUAP              จวบ
5648  5649          918          BU KIT              NaN
5649  5650          918     MARUE BO OK              NaN

[5650 rows x 4 columns]

In [78]:
sub_dis_mas['isActive'] = 1
sub_dis_mas['createdon']= ''
sub_dis_mas['modifiedon']= ''
sub_dis_mas['createdby']= ''
sub_dis_mas['modifiedby']= ''
sub_dis_mas['CountryID'] =  7
sub_dis_mas

,ID,district_id,Sub-Dist. (Eng),Sub-Dist. (Thai),isActive,createdon,modifiedon,createdby,modifiedby,CountryID
0,1,1,THALE CHUP SON,ทะเลชุบศร,1,,,,,7
1,2,1,THA HIN,ท่าหิน,1,,,,,7
2,3,1,KOK KO,กกโก,1,,,,,7
3,4,1,KONG THANU,โก่งธนู,1,,,,,7
4,5,1,KHAO PHRA NGAM,เขาพระงาม,1,,,,,7
...,...,...,...,...,...,...,...,...,...,...
5645,5646,917,DU SONG YO,NaN,1,,,,,7
5646,5647,917,PHADUNG MAT,ผดุงมาตร,1,,,,,7
5647,5648,918,CHUAP,จวบ,1,,,,,7
5648,5649,918,BU KIT,NaN,1,,,,,7
5649,5650,918,MARUE BO OK,NaN,1,,,,,7

In [79]:
sub_dis_mas['createdon']= datetime.now()
sub_dis_mas['modifiedon'] = pd.to_datetime(sub_dis_mas['modifiedon'],errors = 'coerce')
sub_dis_mas['createdon'] = pd.to_datetime(sub_dis_mas['createdon'],errors = 'coerce')
sub_dis_mas

,ID,district_id,Sub-Dist. (Eng),Sub-Dist. (Thai),isActive,createdon,modifiedon,createdby,modifiedby,CountryID
0,1,1,THALE CHUP SON,ทะเลชุบศร,1,2025-11-27 16:36:01.972800,NaT,,,7
1,2,1,THA HIN,ท่าหิน,1,2025-11-27 16:36:01.972800,NaT,,,7
2,3,1,KOK KO,กกโก,1,2025-11-27 16:36:01.972800,NaT,,,7
3,4,1,KONG THANU,โก่งธนู,1,2025-11-27 16:36:01.972800,NaT,,,7
4,5,1,KHAO PHRA NGAM,เขาพระงาม,1,2025-11-27 16:36:01.972800,NaT,,,7
...,...,...,...,...,...,...,...,...,...,...
5645,5646,917,DU SONG YO,NaN,1,2025-11-27 16:36:01.972800,NaT,,,7
5646,5647,917,PHADUNG MAT,ผดุงมาตร,1,2025-11-27 16:36:01.972800,NaT,,,7
5647,5648,918,CHUAP,จวบ,1,2025-11-27 16:36:01.972800,NaT,,,7
5648,5649,918,BU KIT,NaN,1,2025-11-27 16:36:01.972800,NaT,,,7
5649,5650,918,MARUE BO OK,NaN,1,2025-11-27 16:36:01.972800,NaT,,,7

In [80]:
sub_dis_mas.nunique()

ID                  5650
district_id          915
Sub-Dist. (Eng)     5650
Sub-Dist. (Thai)    5588
isActive               1
createdon              1
modifiedon             0
createdby              1
modifiedby             1
CountryID              1
dtype: int64

In [81]:
sub_dis_mas

,ID,district_id,Sub-Dist. (Eng),Sub-Dist. (Thai),isActive,createdon,modifiedon,createdby,modifiedby,CountryID
0,1,1,THALE CHUP SON,ทะเลชุบศร,1,2025-11-27 16:36:01.972800,NaT,,,7
1,2,1,THA HIN,ท่าหิน,1,2025-11-27 16:36:01.972800,NaT,,,7
2,3,1,KOK KO,กกโก,1,2025-11-27 16:36:01.972800,NaT,,,7
3,4,1,KONG THANU,โก่งธนู,1,2025-11-27 16:36:01.972800,NaT,,,7
4,5,1,KHAO PHRA NGAM,เขาพระงาม,1,2025-11-27 16:36:01.972800,NaT,,,7
...,...,...,...,...,...,...,...,...,...,...
5645,5646,917,DU SONG YO,NaN,1,2025-11-27 16:36:01.972800,NaT,,,7
5646,5647,917,PHADUNG MAT,ผดุงมาตร,1,2025-11-27 16:36:01.972800,NaT,,,7
5647,5648,918,CHUAP,จวบ,1,2025-11-27 16:36:01.972800,NaT,,,7
5648,5649,918,BU KIT,NaN,1,2025-11-27 16:36:01.972800,NaT,,,7
5649,5650,918,MARUE BO OK,NaN,1,2025-11-27 16:36:01.972800,NaT,,,7