In [1]:
import pandas as pd

In [5]:
xyz = pd.ExcelFile('/home/ananta/personnel_study_material/practice-and-projects/regular_practice/day_2/Fw_ CP Master Data Update with New Structure 17Sep2025/Master Data (19June2025) v1 for New App.xlsx')
print(xyz.sheet_names)

['Indexing', 'Roles Hierarchy', 'Zone to Territory', 'Location Wise Resource Seed', 'Location Wise Resource CP', 'New Location Wise Resource CP', 'Resource Details Seed', 'Resource Details CP', 'New Resource Details CP', 'TSM Seed', 'TSM CP', 'New TSM CP', 'List of Dealers Seed', 'List of Dealers CP', 'New List of Dealers CP', 'Seed Products', 'CP Products', 'CP and Seed Conversion', 'Product & crops', 'Corteva&Competion Product&Price', 'Season Wise Crops', 'Seasons', 'Crop Wise Stages', 'Crop Wise Pest or Diseases', 'Farmer or Retailer Concent', 'Activity Target Template Seed', 'Activity Target Template CP', 'Seed - Sales Target', 'Campaign Master', 'Activity Access w.r.t. Role', 'Dashboard Sample for DG and TSM', 'Activities Name', 'CP - Sales Target', 'Advisory Visit Reasons', 'Sheet1']

In [2]:
farmer_master = pd.read_excel('/home/ananta/personnel_study_material/practice-and-projects/regular_practice/day_2/Fw_ CP Master Data Update with New Structure 17Sep2025/Master Data (19June2025) v1 for New App.xlsx')

In [ ]:
'Location Wise Resource CP', 'New Location Wise Resource CP'

In [12]:
Location_Wise_Resource_CP = pd.read_excel('/home/ananta/personnel_study_material/practice-and-projects/regular_practice/day_2/Fw_ CP Master Data Update with New Structure 17Sep2025/Master Data (19June2025) v1 for New App.xlsx', sheet_name='Location Wise Resource CP', header=2)
Location_Wise_Resource_CP

,Country,Province,District,Tehsil,UC Name,UC ID,BU,Region,Territory,NSM Name,RSM Name,TSM Name
0,Pakistan,Punjab,Okara,Depalpur,Mahanat Darshan,2908,CP,North,Basirpur,Akram Baluch,Muhamamd Shafiq Ur Rehman,Muhammad Hasnat Zafar
1,Pakistan,Punjab,Okara,Depalpur,Jamal Kot,2909,CP,North,Basirpur,Akram Baluch,Muhamamd Shafiq Ur Rehman,Muhammad Hasnat Zafar
2,Pakistan,Punjab,Okara,Depalpur,Nehal Muhar,2910,CP,North,Basirpur,Akram Baluch,Muhamamd Shafiq Ur Rehman,Muhammad Hasnat Zafar
3,Pakistan,Punjab,Okara,Depalpur,Nama Jinday Ka,2911,CP,North,Basirpur,Akram Baluch,Muhamamd Shafiq Ur Rehman,Muhammad Hasnat Zafar
4,Pakistan,Punjab,Okara,Depalpur,Hakumat Garh,2912,CP,North,Basirpur,Akram Baluch,Muhamamd Shafiq Ur Rehman,Muhammad Hasnat Zafar
...,...,...,...,...,...,...,...,...,...,...,...,...
5418,Pakistan,Sindh,Kashmore,Kashmore,Kashmore Colony 1,1233,NaN,NaN,NaN,NaN,NaN,NaN
5419,Pakistan,Sindh,Kashmore,Kashmore,Gulanpur,1234,NaN,NaN,NaN,NaN,NaN,NaN
5420,Pakistan,Sindh,Kashmore,Kashmore,K.s.ali Bilawal Khan Domki,1235,NaN,NaN,NaN,NaN,NaN,NaN
5421,Pakistan,Sindh,Kashmore,Kashmore,Sodhi,1236,NaN,NaN,NaN,NaN,NaN,NaN
5422,Pakistan,Sindh,Kashmore,Kashmore,Gihalpur,1237,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
New_Location_Wise_Resource_CP = pd.read_excel('/home/ananta/personnel_study_material/practice-and-projects/regular_practice/day_2/Fw_ CP Master Data Update with New Structure 17Sep2025/Master Data (19June2025) v1 for New App.xlsx', sheet_name='New Location Wise Resource CP', header=2)
New_Location_Wise_Resource_CP

,Country,Province,District,Tehsil,UC Name,UC ID,BU,Region,Territory,NSM Name,RSM Name,TSM Name
0,Pakistan,Punjab,Okara,Depalpur,Mahanat Darshan,2908,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant
1,Pakistan,Punjab,Okara,Depalpur,Jamal Kot,2909,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant
2,Pakistan,Punjab,Okara,Depalpur,Nehal Muhar,2910,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant
3,Pakistan,Punjab,Okara,Depalpur,Nama Jinday Ka,2911,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant
4,Pakistan,Punjab,Okara,Depalpur,Hakumat Garh,2912,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant
...,...,...,...,...,...,...,...,...,...,...,...,...
5418,Pakistan,Sindh,Kashmore,Kashmore,Kashmore Colony 1,1233,NaN,NaN,NaN,NaN,NaN,NaN
5419,Pakistan,Sindh,Kashmore,Kashmore,Gulanpur,1234,NaN,NaN,NaN,NaN,NaN,NaN
5420,Pakistan,Sindh,Kashmore,Kashmore,K.s.ali Bilawal Khan Domki,1235,NaN,NaN,NaN,NaN,NaN,NaN
5421,Pakistan,Sindh,Kashmore,Kashmore,Sodhi,1236,NaN,NaN,NaN,NaN,NaN,NaN
5422,Pakistan,Sindh,Kashmore,Kashmore,Gihalpur,1237,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
merge_both = pd.merge(Location_Wise_Resource_CP,New_Location_Wise_Resource_CP, on= ['UC ID'], how='left')

In [15]:
merge_both.isna().sum()

Country_x         0
Province_x        0
District_x        0
Tehsil_x        178
UC Name_x       110
UC ID             0
BU_x           1672
Region_x       1672
Territory_x    1672
NSM Name_x     1672
RSM Name_x     1672
TSM Name_x     1672
Country_y         0
Province_y        0
District_y        0
Tehsil_y        178
UC Name_y       110
BU_y           1672
Region_y       1672
Territory_y    1672
NSM Name_y     1672
RSM Name_y     1672
TSM Name_y     1672
dtype: int64

In [14]:
print(merge_both.columns)
New_Location_Wise_Resource_CP.columns

Index(['Country_x', 'Province_x', 'District_x', 'Tehsil_x', 'UC Name_x',
       'UC ID', 'BU_x', 'Region_x', 'Territory_x', 'NSM Name_x', 'RSM Name_x',
       'TSM Name_x', 'Country_y', 'Province_y', 'District_y', 'Tehsil_y',
       'UC Name_y', 'BU_y', 'Region_y', 'Territory_y', 'NSM Name_y',
       'RSM Name_y', 'TSM Name_y'],
      dtype='object')

Index(['Country', 'Province', 'District', 'Tehsil', 'UC Name', 'UC ID', 'BU',
       'Region', 'Territory', 'NSM Name', 'RSM Name', 'TSM Name'],
      dtype='object')

In [16]:
merge_both['Region_x'].unique()

array(['North', 'South', nan], dtype=object)

In [17]:
merge_both['Region_y'].unique()

array(['Central', 'North', 'South', nan], dtype=object)

In [ ]:
merge_both['Region_new'] = merge_both['Region_y']
merge_both['Territory_y_new'] = merge_both['Region_y']

merge_both

,Country_x,Province_x,District_x,Tehsil_x,UC Name_x,UC ID,BU_x,Region_x,Territory_x,NSM Name_x,...,District_y,Tehsil_y,UC Name_y,BU_y,Region_y,Territory_y,NSM Name_y,RSM Name_y,TSM Name_y,Region_new
0,Pakistan,Punjab,Okara,Depalpur,Mahanat Darshan,2908,CP,North,Basirpur,Akram Baluch,...,Okara,Depalpur,Mahanat Darshan,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant,Central
1,Pakistan,Punjab,Okara,Depalpur,Jamal Kot,2909,CP,North,Basirpur,Akram Baluch,...,Okara,Depalpur,Jamal Kot,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant,Central
2,Pakistan,Punjab,Okara,Depalpur,Nehal Muhar,2910,CP,North,Basirpur,Akram Baluch,...,Okara,Depalpur,Nehal Muhar,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant,Central
3,Pakistan,Punjab,Okara,Depalpur,Nama Jinday Ka,2911,CP,North,Basirpur,Akram Baluch,...,Okara,Depalpur,Nama Jinday Ka,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant,Central
4,Pakistan,Punjab,Okara,Depalpur,Hakumat Garh,2912,CP,North,Basirpur,Akram Baluch,...,Okara,Depalpur,Hakumat Garh,CP,Central,Basirpur,Akram Baluch,Qualib Hussain,Vacant,Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5418,Pakistan,Sindh,Kashmore,Kashmore,Kashmore Colony 1,1233,NaN,NaN,NaN,NaN,...,Kashmore,Kashmore,Kashmore Colony 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5419,Pakistan,Sindh,Kashmore,Kashmore,Gulanpur,1234,NaN,NaN,NaN,NaN,...,Kashmore,Kashmore,Gulanpur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5420,Pakistan,Sindh,Kashmore,Kashmore,K.s.ali Bilawal Khan Domki,1235,NaN,NaN,NaN,NaN,...,Kashmore,Kashmore,K.s.ali Bilawal Khan Domki,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5421,Pakistan,Sindh,Kashmore,Kashmore,Sodhi,1236,NaN,NaN,NaN,NaN,...,Kashmore,Kashmore,Sodhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5422,Pakistan,Sindh,Kashmore,Kashmore,Gihalpur,1237,NaN,NaN,NaN,NaN,...,Kashmore,Kashmore,Gihalpur,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(merge_both['District_x'].unique()) -
merge_both['District_y'].unique()

['Okara' 'Chiniot' 'Faisalabad' 'Gujranwala' 'Hafizabad' 'Mandi Bahauddin'
 'Gujrat' 'Jhelum' 'Jhang' 'Sargodha' 'Sheikhupura' 'Kasur'
 'Nankana Sahib' 'Narowal' 'Sialkot' 'Lahore' 'Toba Tek Singh'
 'Bahawalpur' 'Pakpattan' 'Vehari' 'Rajanpur' 'Dera Ghazi Khan' 'Bhakkar'
 'Mianwali' 'Layyah' 'Muzaffargarh' 'Lodhran' 'Khanewal' 'Bahawalnagar'
 'Multan' 'Rahim Yar Khan' 'Sahiwal' 'Hyderabad' 'Mirpur Khas' 'Attack'
 'Chawal' 'Khushab' 'Rawalpindi' 'Tharparkar' 'Jamshoro' 'Kashmore'
 'Khairpur' 'Larkana' 'Matiari' 'Naushahro Feroze' 'Qambar Shahdadkot'
 'Shikarpur' 'Jacobabad' 'Sukkur' 'Tando Muhammad Khan' 'Thatta' 'Sujawal'
 'Dadu' 'Ghotki' 'Badin' 'Tando Allahyar' 'Sanghar' 'Shaheed Benazirabad'
 'Umerkot' 'Karachi Malir' 'Karachi Korangi' 'Karachi East' 'Karachi West'
 'Karachi South' 'Karachi Cantonment']

array(['Okara', 'Chiniot', 'Faisalabad', 'Gujranwala', 'Hafizabad',
       'Mandi Bahauddin', 'Gujrat', 'Jhelum', 'Jhang', 'Sargodha',
       'Sheikhupura', 'Kasur', 'Nankana Sahib', 'Narowal', 'Sialkot',
       'Lahore', 'Toba Tek Singh', 'Bahawalpur', 'Pakpattan', 'Vehari',
       'Rajanpur', 'Dera Ghazi Khan', 'Bhakkar', 'Mianwali', 'Layyah',
       'Muzaffargarh', 'Lodhran', 'Khanewal', 'Bahawalnagar', 'Multan',
       'Rahim Yar Khan', 'Sahiwal', 'Hyderabad', 'Mirpur Khas', 'Attack',
       'Chawal', 'Khushab', 'Rawalpindi', 'Tharparkar', 'Jamshoro',
       'Kashmore', 'Khairpur', 'Larkana', 'Matiari', 'Naushahro Feroze',
       'Qambar Shahdadkot', 'Shikarpur', 'Jacobabad', 'Sukkur',
       'Tando Muhammad Khan', 'Thatta', 'Sujawal', 'Dadu', 'Ghotki',
       'Badin', 'Tando Allahyar', 'Sanghar', 'Shaheed Benazirabad',
       'Umerkot', 'Karachi Malir', 'Karachi Korangi', 'Karachi East',
       'Karachi West', 'Karachi South', 'Karachi Cantonment'],
      dtype=object)