In [1]:
import pandas as pd
import datetime

In [2]:
thai_farmer_master = pd.read_csv('/home/ananta/personnel_study_material/practice-and-projects/regular_practice/Thai_farmer_master.csv')

In [3]:
thai_farmer_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20688 entries, 0 to 20687
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FARMER NAME       13735 non-null  object
 1   FARMER LAST NAME  13251 non-null  object
 2   ZoneId            13735 non-null  float64
 3   TERRITORYId       5709 non-null   float64
 4   BUID              3796 non-null   float64
 5   DeptID            3796 non-null   float64
 6   ProvienceId       13225 non-null  float64
 7   DistrictId        12336 non-null  float64
 8   SubdistrictId     9503 non-null   float64
 9   FarmercategoryID  13735 non-null  float64
 10  VILLAGE NAME      11567 non-null  object
 11  HOME NO.          12483 non-null  object
 12  TELEPHONE NO.     6414 non-null   object
 13  MDO               12078 non-null  object
 14  DSM               13257 non-null  object
 15  LINE CONTACT      112 non-null    object
 16  FACE BOOK         47 non-null     object
 17  MDO_ID            3796 non-null   float64
 18  DSM_ID            7331 non-null   float64
 19  isActive          20688 non-null  int64
 20  createdon         0 non-null      float64
 21  modifiedon        0 non-null      float64
 22  createdby         20688 non-null  object
 23  modifiedby        0 non-null      float64
 24  CountryID         20688 non-null  int64
dtypes: float64(13), int64(2), object(10)
memory usage: 3.9+ MB

In [4]:
thai_farmer_master.columns

Index(['FARMER NAME', 'FARMER LAST NAME', 'ZoneId', 'TERRITORYId', 'BUID',
       'DeptID', 'ProvienceId', 'DistrictId', 'SubdistrictId',
       'FarmercategoryID', 'VILLAGE NAME', 'HOME NO.', 'TELEPHONE NO.', 'MDO',
       'DSM', 'LINE CONTACT', 'FACE BOOK', 'MDO_ID', 'DSM_ID', 'isActive',
       'createdon', 'modifiedon', 'createdby', 'modifiedby', 'CountryID'],
      dtype='object')

In [5]:
thai_farmer_master = thai_farmer_master[['FARMER NAME', 'FARMER LAST NAME','VILLAGE NAME', 'HOME NO.', 'TELEPHONE NO.', 'MDO',
       'DSM', 'LINE CONTACT', 'FACE BOOK', 'isActive',
       'CountryID']]
thai_farmer_master.columns

Index(['FARMER NAME', 'FARMER LAST NAME', 'VILLAGE NAME', 'HOME NO.',
       'TELEPHONE NO.', 'MDO', 'DSM', 'LINE CONTACT', 'FACE BOOK', 'isActive',
       'CountryID'],
      dtype='object')

In [6]:
thai_farmer_master

,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID
0,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7
1,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7
2,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7
3,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7
4,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7
...,...,...,...,...,...,...,...,...,...,...,...
20683,นายสายัณห์,สวนสี,แม่สลิด1,NaN,614094433.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7
20684,นางสาวธิดารัตน์,จันทร์โท,แม่สลิด1,NaN,859033655.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7
20685,คำปัน,เมืองจันทร์หอม,พระธาตุผาแดง,NaN,826181952.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7
20686,รัฐพล,ภูมิพระธาตุ,ขเนจื้อ,NaN,930362254.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7
20687,ผ่องศรี,คำปา,แม่สลิด1,NaN,823497974.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7

In [7]:
thai_farmer_master.columns

Index(['FARMER NAME', 'FARMER LAST NAME', 'VILLAGE NAME', 'HOME NO.',
       'TELEPHONE NO.', 'MDO', 'DSM', 'LINE CONTACT', 'FACE BOOK', 'isActive',
       'CountryID'],
      dtype='object')

In [8]:
thai_farmer_master['createdby'] = 'Admin'
thai_farmer_master.columns

Index(['FARMER NAME', 'FARMER LAST NAME', 'VILLAGE NAME', 'HOME NO.',
       'TELEPHONE NO.', 'MDO', 'DSM', 'LINE CONTACT', 'FACE BOOK', 'isActive',
       'CountryID', 'createdby'],
      dtype='object')

In [9]:
thai_farmer_master.head()

,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby
0,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin
1,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin
2,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin
3,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin
4,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin

In [10]:
thai_farmer_master['created_on'] = datetime.datetime.now()
thai_farmer_master.head()

,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on
0,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963
1,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963
2,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963
3,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963
4,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963

In [11]:
thai_farmer_master['modified_on'] = datetime.datetime.now()
thai_farmer_master.head()

,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on
0,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444
1,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444
2,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444
3,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444
4,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444

In [12]:
thai_farmer_master['modified_by'] = 'null'
thai_farmer_master.head()

,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on,modified_by
0,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
1,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
2,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
3,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
4,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null

In [13]:
thai_farmer_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20688 entries, 0 to 20687
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FARMER NAME       13735 non-null  object
 1   FARMER LAST NAME  13251 non-null  object
 2   VILLAGE NAME      11567 non-null  object
 3   HOME NO.          12483 non-null  object
 4   TELEPHONE NO.     6414 non-null   object
 5   MDO               12078 non-null  object
 6   DSM               13257 non-null  object
 7   LINE CONTACT      112 non-null    object
 8   FACE BOOK         47 non-null     object
 9   isActive          20688 non-null  int64
 10  CountryID         20688 non-null  int64
 11  createdby         20688 non-null  object
 12  created_on        20688 non-null  datetime64[us]
 13  modified_on       20688 non-null  datetime64[us]
 14  modified_by       20688 non-null  object
dtypes: datetime64[us](2), int64(2), object(11)
memory usage: 2.4+ MB

In [14]:
thai_farmer_master['FARMER_ID'] = range(1, len(thai_farmer_master) + 1)
thai_farmer_master.head()

,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on,modified_by,FARMER_ID
0,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,1
1,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,2
2,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,3
3,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,4
4,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,5

In [15]:
cols = thai_farmer_master.columns.tolist()
cols.insert(0, cols.pop())
thai_farmer_master = thai_farmer_master[cols]
print(thai_farmer_master.columns)

Index(['FARMER_ID', 'FARMER NAME', 'FARMER LAST NAME', 'VILLAGE NAME',
       'HOME NO.', 'TELEPHONE NO.', 'MDO', 'DSM', 'LINE CONTACT', 'FACE BOOK',
       'isActive', 'CountryID', 'createdby', 'created_on', 'modified_on',
       'modified_by'],
      dtype='object')

In [16]:
thai_farmer_master.columns

Index(['FARMER_ID', 'FARMER NAME', 'FARMER LAST NAME', 'VILLAGE NAME',
       'HOME NO.', 'TELEPHONE NO.', 'MDO', 'DSM', 'LINE CONTACT', 'FACE BOOK',
       'isActive', 'CountryID', 'createdby', 'created_on', 'modified_on',
       'modified_by'],
      dtype='object')

In [17]:
filtered = thai_farmer_master[
    (thai_farmer_master['FARMER NAME'] == 'SANAN') &
    (thai_farmer_master['FARMER LAST NAME'] == 'DUANGKAEW')
]

In [18]:
thai_farmer_master

,FARMER_ID,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on,modified_by
0,1,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
1,2,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
2,3,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
3,4,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
4,5,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20683,20684,นายสายัณห์,สวนสี,แม่สลิด1,NaN,614094433.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20684,20685,นางสาวธิดารัตน์,จันทร์โท,แม่สลิด1,NaN,859033655.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20685,20686,คำปัน,เมืองจันทร์หอม,พระธาตุผาแดง,NaN,826181952.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20686,20687,รัฐพล,ภูมิพระธาตุ,ขเนจื้อ,NaN,930362254.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20687,20688,ผ่องศรี,คำปา,แม่สลิด1,NaN,823497974.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null

In [19]:
intermidate_employee = pd.read_csv('/home/ananta/personnel_study_material/practice-and-projects/regular_practice/intermediate_employee_master_Thai.csv')

In [20]:
intermidate_employee.columns

Index(['EMP_ID', 'EMP_Name', 'Telephone Number', 'Business Unit', 'roleName',
       'Email Address', 'BUID'],
      dtype='object')

In [21]:
thai_farmer_master.columns

Index(['FARMER_ID', 'FARMER NAME', 'FARMER LAST NAME', 'VILLAGE NAME',
       'HOME NO.', 'TELEPHONE NO.', 'MDO', 'DSM', 'LINE CONTACT', 'FACE BOOK',
       'isActive', 'CountryID', 'createdby', 'created_on', 'modified_on',
       'modified_by'],
      dtype='object')

In [22]:
intermidate_employee

,EMP_ID,EMP_Name,Telephone Number,Business Unit,roleName,Email Address,BUID
0,1,VACANT,NaN,CP,MDO,NaN,1.0
1,2,NATTARAT MATURA,837615100.0,CP,MDO,NaN,1.0
2,3,SITTHICHAI PHONGSRI,917435971.0,CP,MDO,NaN,1.0
3,4,NAPHATSORN POMLOI,902439218.0,CP,MDO,NaN,1.0
4,5,ANUPHONG JUNJUY,863089244.0,CP,MDO,NaN,1.0
...,...,...,...,...,...,...,...
61,62,PHONGPHAT SRITATERA,839661197.0,NaN,NCO,NaN,NaN
62,63,TAWEE SAENGWIJIT,862460272.0,NaN,NCO,NaN,NaN
63,64,THANAKORN THONGTHAI,981505590.0,NaN,NCO,NaN,NaN
64,65,RANGSAN NONG-NGOK,837489418.0,NaN,NCO,NaN,NaN
65,66,APIWAT SUKSUPHAET,871253373.0,NaN,NCO,NaN,NaN

In [23]:
thai_farmer_master

,FARMER_ID,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on,modified_by
0,1,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
1,2,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
2,3,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
3,4,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
4,5,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20683,20684,นายสายัณห์,สวนสี,แม่สลิด1,NaN,614094433.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20684,20685,นางสาวธิดารัตน์,จันทร์โท,แม่สลิด1,NaN,859033655.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20685,20686,คำปัน,เมืองจันทร์หอม,พระธาตุผาแดง,NaN,826181952.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20686,20687,รัฐพล,ภูมิพระธาตุ,ขเนจื้อ,NaN,930362254.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null
20687,20688,ผ่องศรี,คำปา,แม่สลิด1,NaN,823497974.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null

In [24]:
thai_farmer_master['MDO'] = thai_farmer_master['MDO'].str.strip().str.upper()
intermidate_employee['EMP_Name'] = intermidate_employee['EMP_Name'].str.strip().str.upper()
#x = pd.merge(thai_farmer_master,intermidate_employee,left_on='MDO',right_on='EMP_Name',how='left')

In [25]:
intermidate_employee.columns

Index(['EMP_ID', 'EMP_Name', 'Telephone Number', 'Business Unit', 'roleName',
       'Email Address', 'BUID'],
      dtype='object')

In [26]:
x = intermidate_employee[['EMP_ID','EMP_Name']].copy()

In [27]:
x

    EMP_ID             EMP_Name
0        1               VACANT
1        2      NATTARAT MATURA
2        3  SITTHICHAI PHONGSRI
3        4    NAPHATSORN POMLOI
4        5      ANUPHONG JUNJUY
..     ...                  ...
61      62  PHONGPHAT SRITATERA
62      63     TAWEE SAENGWIJIT
63      64  THANAKORN THONGTHAI
64      65    RANGSAN NONG-NGOK
65      66    APIWAT SUKSUPHAET

[66 rows x 2 columns]

In [32]:
print(thai_farmer_master.columns)
x.columns

Index(['FARMER_ID', 'FARMER NAME', 'FARMER LAST NAME', 'VILLAGE NAME',
       'HOME NO.', 'TELEPHONE NO.', 'MDO', 'DSM', 'LINE CONTACT', 'FACE BOOK',
       'isActive', 'CountryID', 'createdby', 'created_on', 'modified_on',
       'modified_by'],
      dtype='object')

Index(['EMP_ID', 'EMP_Name'], dtype='object')

In [ ]:
x['EMP_Name']

0                  VACANT
1         NATTARAT MATURA
2     SITTHICHAI PHONGSRI
3       NAPHATSORN POMLOI
4         ANUPHONG JUNJUY
             ...
61    PHONGPHAT SRITATERA
62       TAWEE SAENGWIJIT
63    THANAKORN THONGTHAI
64      RANGSAN NONG-NGOK
65      APIWAT SUKSUPHAET
Name: EMP_Name, Length: 66, dtype: object

In [36]:
print(thai_farmer_master.shape)
x.shape

(20688, 16)

(66, 2)

In [35]:
x = x.rename(columns={"EMP_Name":"MDO"})

In [38]:
new  = pd.merge(thai_farmer_master,x, on = ['MDO'], how ='left')
new

,FARMER_ID,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on,modified_by,EMP_ID
0,1,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
1,2,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
2,3,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
3,4,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
4,5,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20683,20684,นายสายัณห์,สวนสี,แม่สลิด1,NaN,614094433.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,42.0
20684,20685,นางสาวธิดารัตน์,จันทร์โท,แม่สลิด1,NaN,859033655.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,42.0
20685,20686,คำปัน,เมืองจันทร์หอม,พระธาตุผาแดง,NaN,826181952.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,42.0
20686,20687,รัฐพล,ภูมิพระธาตุ,ขเนจื้อ,NaN,930362254.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,42.0
20687,20688,ผ่องศรี,คำปา,แม่สลิด1,NaN,823497974.0,DAMRONGSAK LOEDRATTANADARA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,42.0

In [41]:
new.head(6)

,FARMER_ID,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on,modified_by,EMP_ID
0,1,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
1,2,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
2,3,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
3,4,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
4,5,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
5,6,สำรวย,สาวรีย์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN

In [42]:
new[new['EMP_ID'].isna()]

,FARMER_ID,FARMER NAME,FARMER LAST NAME,VILLAGE NAME,HOME NO.,TELEPHONE NO.,MDO,DSM,LINE CONTACT,FACE BOOK,isActive,CountryID,createdby,created_on,modified_on,modified_by,EMP_ID
0,1,ดวงมาลย์,ไชยแสง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
1,2,จิราพร,น้อยพันธุ์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
2,3,วิไลลักษณ์,ฉายฉันท์,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
3,4,เจริญพงษ์,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
4,5,ธงไชย,การีหว่าง,NaN,NaN,NaN,ANUCHA POSRITHONG,MR.PORNSAWAN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20501,20502,วีรชัย,กองมณี,บ้านหินซ้อนใต้,116/2,904269566.0,ANUCHA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
20502,20503,สุภาพร,กอมมณี,บ้านหินซ้อนใต้,116/2,899030019.0,ANUCHA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
20503,20504,พิษณุ,แสงอรุณ,บ้านซับครก,80/1,898087051.0,ANUCHA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
20504,20505,อำนวย,สุขสี,NaN,83/3,627878292.0,ANUCHA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN
20505,20506,ณรงค์,กลิ่นต่าย,บ้านบ้านบ่อมะแฟน,31/2,898054382.0,ANUCHA,NaN,NaN,NaN,1,7,Admin,2025-10-14 11:10:30.170963,2025-10-14 11:10:30.194444,null,NaN

In [31]:
y = x.rename(columns={'Emp_id': 'MDO_ID'}) 
y = x.drop(columns=['EMP_Name']) 
y

    EMP_ID
0        1
1        2
2        3
3        4
4        5
..     ...
61      62
62      63
63      64
64      65
65      66

[66 rows x 1 columns]

In [48]:
th_far_mas = pd.read_csv("Thai_farmer_master.csv")
th_far_mas.columns

Index(['FARMER NAME', 'FARMER LAST NAME', 'ZoneId', 'TERRITORYId', 'BUID',
       'DeptID', 'ProvienceId', 'DistrictId', 'SubdistrictId',
       'FarmercategoryID', 'VILLAGE NAME', 'HOME NO.', 'TELEPHONE NO.', 'MDO',
       'DSM', 'LINE CONTACT', 'FACE BOOK', 'MDO_ID', 'DSM_ID', 'isActive',
       'createdon', 'modifiedon', 'createdby', 'modifiedby', 'CountryID'],
      dtype='object')

In [49]:
emp_mas = pd.read_csv("Thai_EMPloyee_master.csv")[['EMP_ID','EMP_Name']]
emp_mas.columns

Index(['EMP_ID', 'EMP_Name'], dtype='object')

In [50]:
emp_mas = emp_mas.rename(columns={"EMP_Name":"MDO"})

emp_mas

    EMP_ID                  MDO
0        1               VACANT
1        2      NATTARAT MATURA
2        3  SITTHICHAI PHONGSRI
3        4    NAPHATSORN POMLOI
4        5      ANUPHONG JUNJUY
..     ...                  ...
61      62  PHONGPHAT SRITATERA
62      63     TAWEE SAENGWIJIT
63      64  THANAKORN THONGTHAI
64      65    RANGSAN NONG-NGOK
65      66    APIWAT SUKSUPHAET

[66 rows x 2 columns]

In [51]:
farmer_new = pd.merge(th_far_mas,emp_mas, on = ['MDO'], how = 'left')
farmer_new.isna().sum()

FARMER NAME          6953
FARMER LAST NAME     7437
ZoneId               6953
TERRITORYId         14979
BUID                16892
DeptID              16892
ProvienceId          7463
DistrictId           8352
SubdistrictId       11185
FarmercategoryID     6953
VILLAGE NAME         9121
HOME NO.             8205
TELEPHONE NO.       14274
MDO                  8610
DSM                  7431
LINE CONTACT        20576
FACE BOOK           20641
MDO_ID              16892
DSM_ID              13357
isActive                0
createdon           20688
modifiedon          20688
createdby               0
modifiedby          20688
CountryID               0
EMP_ID              16892
dtype: int64

In [52]:
farmer_new

,FARMER NAME,FARMER LAST NAME,ZoneId,TERRITORYId,BUID,DeptID,ProvienceId,DistrictId,SubdistrictId,FarmercategoryID,...,FACE BOOK,MDO_ID,DSM_ID,isActive,createdon,modifiedon,createdby,modifiedby,CountryID,EMP_ID
0,ดวงมาลย์,ไชยแสง,1.0,NaN,NaN,NaN,2.0,13.0,140.0,1.0,...,NaN,NaN,NaN,1,NaN,NaN,Admin,NaN,7,NaN
1,จิราพร,น้อยพันธุ์,1.0,NaN,NaN,NaN,2.0,13.0,140.0,1.0,...,NaN,NaN,NaN,1,NaN,NaN,Admin,NaN,7,NaN
2,วิไลลักษณ์,ฉายฉันท์,1.0,NaN,NaN,NaN,2.0,13.0,140.0,1.0,...,NaN,NaN,NaN,1,NaN,NaN,Admin,NaN,7,NaN
3,เจริญพงษ์,การีหว่าง,1.0,NaN,NaN,NaN,2.0,13.0,140.0,1.0,...,NaN,NaN,NaN,1,NaN,NaN,Admin,NaN,7,NaN
4,ธงไชย,การีหว่าง,1.0,NaN,NaN,NaN,2.0,13.0,140.0,1.0,...,NaN,NaN,NaN,1,NaN,NaN,Admin,NaN,7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20683,นายสายัณห์,สวนสี,6.0,13.0,2.0,1.0,26.0,341.0,2344.0,3.0,...,NaN,42.0,NaN,1,NaN,NaN,Admin,NaN,7,42.0
20684,นางสาวธิดารัตน์,จันทร์โท,6.0,13.0,2.0,1.0,26.0,341.0,2344.0,3.0,...,NaN,42.0,NaN,1,NaN,NaN,Admin,NaN,7,42.0
20685,คำปัน,เมืองจันทร์หอม,6.0,13.0,2.0,1.0,26.0,345.0,2371.0,3.0,...,NaN,42.0,NaN,1,NaN,NaN,Admin,NaN,7,42.0
20686,รัฐพล,ภูมิพระธาตุ,6.0,13.0,2.0,1.0,26.0,343.0,2355.0,3.0,...,NaN,42.0,NaN,1,NaN,NaN,Admin,NaN,7,42.0
20687,ผ่องศรี,คำปา,6.0,13.0,2.0,1.0,26.0,341.0,2344.0,3.0,...,NaN,42.0,NaN,1,NaN,NaN,Admin,NaN,7,42.0

In [58]:
temp = farmer_new[['MDO','MDO_ID']]

In [59]:
temp[temp['MDO_ID']==20]

                 MDO  MDO_ID
20256  WARIT SURAKUN    20.0
20257  WARIT SURAKUN    20.0
20258  WARIT SURAKUN    20.0
20259  WARIT SURAKUN    20.0
20260  WARIT SURAKUN    20.0
20261  WARIT SURAKUN    20.0
20262  WARIT SURAKUN    20.0
20263  WARIT SURAKUN    20.0
20264  WARIT SURAKUN    20.0
20265  WARIT SURAKUN    20.0
20266  WARIT SURAKUN    20.0
20267  WARIT SURAKUN    20.0
20268  WARIT SURAKUN    20.0
20269  WARIT SURAKUN    20.0
20270  WARIT SURAKUN    20.0

In [55]:
farmer_new['MDO_ID'].unique()

array([nan, 21., 28., 22., 19., 27., 20., 63., 38., 40., 37., 34., 33.,
       35., 43., 42.])